-- CreateEnum
CREATE TYPE "FileCategory" AS ENUM ('TASK_ATTACHMENT', 'TASK_SUBMISSION', 'DAILY_REPORT', 'PROFILE_PICTURE', 'ANNOUNCEMENT', 'EMPLOYEE_DOCUMENT', 'SUPPORT_TICKET', 'OTHER');

-- AlterTable
ALTER TABLE "StoredFile" ADD COLUMN     "category" "FileCategory" NOT NULL DEFAULT 'OTHER';
